<?php
/**
 * Versionsstand der Anwendung und Änderungsverlauf (Versionsübersicht im Adminbereich).
 *
 * Schema: erste Stelle für große Ausbaustufen (1.0, 2.0, 3.0 ...), zweite Stelle für kleinere
 * Ergänzungen und Korrekturen (2.1, 2.2 ...). Jeder Eintrag nennt Datum, Art (Neu, Geändert, Behoben)
 * und kurze Erklärung. Bei jedem Release die Konstante APP_VERSION und die Liste ergänzen.
 */
declare(strict_types=1);

const APP_VERSION = '4.28';

/** Änderungsverlauf, neueste Version zuerst. */
function app_changelog(): array
{
    return [
        ['version' => '4.28', 'date' => '07.09.2026', 'title' => 'restart-workers.sh respektiert die Deploy-Sperre',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'restart-workers.sh konnte parallel zu einem laufenden Deployment Container mit dem alten Release neu erzeugen (Lauf #63 scheiterte an der Release-Bindung). Das Skript nutzt jetzt dieselbe Sperre wie deploy-runner.sh: Es bricht ab, wenn ein Deployment läuft, und blockiert seinerseits den Start eines Deployments, solange es arbeitet.'],
         ]],
        ['version' => '4.27', 'date' => '07.09.2026', 'title' => 'Gegenprobe in restart-workers.sh korrigiert',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Die Gegenprobe am Ende von restart-workers.sh lud config.php direkt und löste deren Schutz gegen Direktaufruf aus (Ausgabe „Forbidden“). Sie nutzt jetzt bin/mail-check.php und zeigt die ersten Zeilen (Versand aktiv, Absender, Antwortadresse).'],
         ]],
        ['version' => '4.26', 'date' => '07.09.2026', 'title' => 'Konfigurationsänderungen erreichen die Container zuverlässig',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'restart-workers.sh startete die Hintergrunddienste nur neu. Weil shared/config.php als Einzeldatei eingebunden ist und sed oder Editoren die Datei mit neuem Inode schreiben, lasen Container weiter den alten Inhalt (mail.enabled blieb im Container false). Das Skript erzeugt die Dienste jetzt neu, prüft den Inode im php-Container, erzeugt diesen bei Abweichung ebenfalls neu oder lädt sonst php-fpm neu (OPcache), prüft vorab die Syntax und zeigt am Ende, welche Werte der Container tatsächlich liest.'],
         ]],
        ['version' => '4.25', 'date' => '07.09.2026', 'title' => 'Mailprüfung warnt bei ungültigen Adressen, Betriebshinweise',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'bin/mail-check.php beschrieb die Wirkung eines abgeschalteten Versands noch mit dem Stand vor 4.22 (Vormerkung antwortet 503). Der Hinweis nennt jetzt das Speichern mit Wartemarke und das Nachsenden durch die Wartung.'],
            ['type' => 'Neu', 'text' => 'bin/mail-check.php warnt, wenn Absender- oder Antwortadresse in der Konfiguration keine gültige E-Mail-Adresse ist (in Produktion fehlte der Antwortadresse die Domainendung).'],
            ['type' => 'Geändert', 'text' => 'Betriebsdokumentation: Prüfschritte zu Hostinger-Firewall und fail2ban-Einheit nach dem SSH-Ausfall von Lauf #58, Hinweis auf RELEASE_SHA für manuelle Compose-Aufrufe und Ablageort der Deploy-Protokolle.'],
         ]],
        ['version' => '4.24', 'date' => '07.09.2026', 'title' => 'Links zugestellter E-Mails bleiben gültig, Mail nach Bestätigung wird nachgesendet',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Ein fehlgeschlagener Wiederversand der Bestätigungsmail (etwa bei nicht aktivem Versand) machte bisher die Bestätigungs- und Abmeldelinks einer bereits zugestellten E-Mail ungültig. Neue Token werden jetzt erst gespeichert, wenn die Mail tatsächlich übergeben wurde.'],
            ['type' => 'Behoben', 'text' => 'Die E-Mail nach der Bestätigung der Vormerkung wurde bei nicht aktivem Versand still verworfen, die Seite behauptete dennoch den Versand. Jetzt bleibt der Abmeldelink der ersten E-Mail gültig, die Seite sagt „Bestätigung per E-Mail folgt, sobald der Versand verfügbar ist“, und die Wartung sendet die Mail mit frischem Abmeldelink nach.'],
         ]],
        ['version' => '4.23', 'date' => '07.09.2026', 'title' => 'Nachsenden vervollständigt, Cron-Frage geklärt',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Nach der adversarialen Prüfung von 4.22: Migration 022 trägt die Wartemarke für vorhandene offene Vormerkungen und Benutzer der letzten 30 Tage nach (sonst wäre der Eintrag des Kunden vom 07.09.2026 nie nachgesendet worden). Die Willkommensmail wird auch nachgesendet, wenn die Adresse bei Registrierung ohne Mailversand bereits als bestätigt gilt (dann ohne Bestätigungslink). Ein erfolgreicher Versand hebt die Wartemarke auf (keine doppelte Mail), erneutes Absenden während des Wartens zeigt weiterhin „Bestätigungs-E-Mail folgt“ statt „Link geschickt“.'],
            ['type' => 'Behoben', 'text' => 'Nachsendungen laufen über die Mail-Warteschlange (Ratenbegrenzung, Circuit Breaker) statt direkt aus dem Wartungsworker; nachgesendete Bestätigungsmails nennen Datum und Herkunft der Eintragung; Einträge älter als 30 Tage werden nicht mehr nachgesendet. „Erneut versuchen“ eines endgültig fehlgeschlagenen Mailjobs wird verweigert, weil dessen Inhalt bereinigt ist; job_mail sendet keine leeren Nachrichten. Kontingenthinweis: Audit „gesendet“ nur bei tatsächlicher Übergabe.'],
            ['type' => 'Neu', 'text' => 'Betriebsfrage Cron: Der VPS braucht keine Cron-Jobs, Scheduler und Worker decken alle Aufgaben ab (Abdeckungsmatrix in docs/vps/06-betrieb.md). Offen: alten IONOS-Cronjob löschen. Konfigurationsänderungen erreichen Dauerprozesse erst nach Neustart: neues Skript deploy/vps/scripts/restart-workers.sh, in docs/mail-einrichtung.md eingebunden.'],
         ]],
        ['version' => '4.22', 'date' => '07.09.2026', 'title' => 'Bestätigungs- und Willkommensmails werden nachgesendet',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Nach der Vorregistrierung erschien „E-Mail konnte nicht gesendet werden, bitte in zehn Minuten erneut versuchen“, obwohl die Ursache der nicht aktive Mailversand in Produktion war (mail.enabled = false). Der Eintrag wird jetzt gespeichert und als wartend markiert; die Seite sagt ehrlich „Vormerkung gespeichert, Bestätigungs-E-Mail folgt“. Die Wartung (Job maintenance stündlich, auf dem Webhosting cron.php) sendet die Bestätigungsmail automatisch nach, sobald der Versand aktiv ist; Token werden dabei neu erzeugt. Migration 021.'],
            ['type' => 'Behoben', 'text' => 'Registrierung: Kann die Willkommensmail nicht erzeugt werden, wird sie als wartend markiert (users.welcome_mail_pending) und nachgesendet, solange die Adresse noch nicht bestätigt ist. Damit erhält jede Registrierung und jede Vorregistrierung eine E-Mail, sobald der Versand eingerichtet ist.'],
            ['type' => 'Neu', 'text' => 'Adminbereich: Warnbanner, wenn der Mailversand nicht aktiv ist, mit der Anzahl wartender Nachsendungen und Verweis auf die Anleitung. Test tools/interest-check.sh um den Nachsende-Fall erweitert.'],
         ]],
        ['version' => '4.21', 'date' => '07.09.2026', 'title' => 'E-Mails im Corporate Design, Willkommensmail, Bestätigung der Vormerkung, Mailprüfung',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'Alle E-Mails (mail_layout) im Corporate Design der Müller Holding AG: Kopfnaht mit Goldsegment, Wortmarke SmartEinzug, Goldbalken, Fließtext Anthrazit, Gold nur als Akzent, Fußband mit den Pflichtangaben nach § 80 AktG (Sitz, Registergericht, HRB 104291, Vorstand, Aufsichtsratsvorsitzender), Zweitlink für Abmeldungen. Textfassung gleichwertig.'],
            ['type' => 'Neu', 'text' => 'Jede Registrierung erhält eine Willkommensmail mit Bestätigungslink und den nächsten Schritten (Zwei-Faktor, Buchhaltungssystem, Stripe). Jede bestätigte Vorregistrierung erhält eine Bestätigungsmail mit Abmeldelink; der Abmeldetoken wird dabei frisch erzeugt.'],
            ['type' => 'Neu', 'text' => 'bin/mail-check.php zeigt den Stand des Mailversands (Passwörter nie im Klartext) und sendet mit --send eine Testmail im Corporate Design. Anleitung docs/mail-einrichtung.md im Adminbereich. Hintergrund: In Produktion steht mail.enabled auf false; damit sendet die Anwendung keine E-Mails und die Vorregistrierung nimmt keine Einträge an.'],
            ['type' => 'Geändert', 'text' => 'Statusseite: Verfügbarkeit zusätzlich „seit Erfassungsbeginn“ mit Tagesangabe, solange die Fenster von 30 und 90 Tagen noch nicht mit Messdaten gefüllt sind. Die Komponente E-Mail bleibt unbekannt, bis der Mailversand aktiviert ist. docs/sevdesk.md um die Checkliste für das sevdesk-Testkonto ergänzt. Test tools/mail-ci-check.php (28 Fälle).'],
         ]],
        ['version' => '4.20', 'date' => '07.09.2026', 'title' => 'sevdesk-Seite als Inhaltsseite, Altreleases bleiben Rollback-Ziel',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'smart-einzug.de/integrationen/sevdesk/ zur vollständigen Inhaltsseite ausgebaut (rund 1.900 Wörter): Ausgangslage, geplanter Ablauf, Nutzen, Zielgruppen, Grundlagen der SEPA-Lastschrift (Mandat, Vorabankündigung, Rücklastschrift, Gläubiger-ID), Voraussetzungen, Vergleich manueller Einzug gegen geplanten Ablauf, Abgrenzung zu Lexware Office, elf Fragen mit FAQ-Markup (schema.org FAQPage), Zeitplan, zwei Formulare. Title und Description auf die Suchbegriffe sevdesk, SEPA-Lastschrift, Stripe ausgerichtet; alle Aussagen zur Anbindung als geplant gekennzeichnet.'],
            ['type' => 'Behoben', 'text' => 'Die Bereinigung in deploy.sh (4.17) löschte beim Deployment b5fcd8d das vollständige Altrelease bdd42e0 (4.16), weil es aus der Zeit vor dem Vollständigkeitsnachweis stammte und keine Markerdatei trug. Vollständige Altreleases (Anwendung, Deploy-Skripte und Statusseite vorhanden) werden jetzt nachträglich als „legacy“ gekennzeichnet und bleiben Rollback-Ziel; gelöscht wird nur erkennbar Unvollständiges. bdd42e0 ist auf dem Server nicht mehr vorhanden; Rollback-Ziel bleibt 54caa37 (4.17).'],
         ]],
        ['version' => '4.19', 'date' => '07.09.2026', 'title' => 'sevdesk-Masterplan Phase 1: Landingpage, Vorregistrierung, Adminverwaltung, Freigabeschalter',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Landingpage smart-einzug.de/integrationen/sevdesk/ nach Masterplan: Status „In Vorbereitung, Start für Ende September 2026 geplant“, geplanter Ablauf in drei Schritten (als Ziel gekennzeichnet), Nutzen, sichtbare Voraussetzungen (sevdesk-API nach offizieller Hilfe im Tarif Buchhaltung Pro, Systemversion 2.0, Prüfung beim Verbindungstest; Stripe SEPA-Basislastschrift, kein B2B), Abgrenzung zu Lexware Office, Fragen, zwei Formulare, Unabhängigkeitshinweis. Startseiten-Teaser „Demnächst: SEPA-Lastschriften für sevdesk“, Übersicht angeglichen.'],
            ['type' => 'Geändert', 'text' => 'Vorregistrierung: getrennte Token für Bestätigung (7 Tage, nach Bestätigung gelöscht) und Abmeldung (dauerhaft), Name optional, Einwilligungstext v3 mit Zweck (Entwicklungsstand, Start, mögliche Betaeinladung) und Verantwortlicher, Texte der Rückmeldungen und der Bestätigungsmail nach Masterplan, freiwillige Angaben nach Bestätigung (Rechnungen je Monat, Stripe-Konto, API-Zugang, Betatest-Interesse), Sperrvermerk (nur E-Mail bleibt), Kennzahlen über funnel_events (Vormerkung abgesendet, bestätigt). Eine Abmeldung wird nie automatisch aufgehoben; erneute Eintragung braucht eine neue Bestätigung.'],
            ['type' => 'Neu', 'text' => 'Adminbereich: Suche, Filter (Status, Herkunft), formelsicherer CSV-Export mit Audit, Einwilligungsnachweis je Eintrag (Fassung, Zeitpunkt), Aktionen Abmelden, Sperren, Löschen und Betaeinladung (nur bestätigt und nicht gesperrt) mit 2FA-Code und Audit; Kennzahlen getrennt: Formularabsendungen, bestätigt, Betatest-Interesse, eingeladen, aktiviert, verbundene Firmen, erste Einzüge; Anzeige der Freigabeschalter.'],
            ['type' => 'Neu', 'text' => 'Freigabeschalter je Integration in platform_settings (sevdesk_public_state, sevdesk_waitlist, sevdesk_connect, sevdesk_collections, sevdesk_writeback; app/integration_state.php). register.php?integration=sevdesk führt vor der Freigabe zur Vorregistrierung; die Vorauswahl kommt aus einer festen Liste und ist nie ein Berechtigungsnachweis. Adapter-Gerüst app/sevdesk.php mit Authorization-Header, ohne Fähigkeiten und mit Sperre bis zur Verifikation mit einem Testkonto (Blocker: kein Testkonto).'],
            ['type' => 'Geändert', 'text' => 'Dokumentation docs/sevdesk.md (Bestandsaufnahme vorhanden/fehlt/kritisch/Schritt, Zielarchitektur, Schalter, Launch und Rollback) im Adminbereich; Datenschutzerklärung 3a erweitert (Verantwortlicher, Zweck, freiwillige Angaben, Sperrvermerk); Einwilligungsarchiv v3. Befund Tarife: Repository einheitlich rollierend, live zeigte lexoffice-einzug.de am 07.09.2026 noch 31.12.2026, Prüfung des Webhosting-Deployments offen.'],
         ]],
        ['version' => '4.18', 'date' => '07.09.2026', 'title' => 'sevdesk-Vorankündigung mit Vormerkung',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Die Seite smart-einzug.de/integrationen/sevdesk/ ist jetzt indexierbar und kündigt die sevdesk-Integration an (in Planung, Start geplant zum 30.09.2026): geplanter Funktionsumfang, Ablauf der Vormerkung, Unterschied zur Lexware-Office-Integration, Fragen und Markenhinweis. Keine Preise, keine Tarifaussagen zu sevdesk, kein Kaufbutton.'],
            ['type' => 'Neu', 'text' => 'Vormerkung (Warteliste) mit Double-Opt-in: Formular auf der Produktseite, Endpunkt vormerken.php, Tabelle interest_registrations (Migration 020). Gespeichert werden E-Mail, optional Firma, Herkunftsseite, Zeitpunkte und die Fassung des Einwilligungstextes; kein Klartext-Token (nur SHA-256), keine IP-Adressen. Bestätigungslink 7 Tage gültig, danach Abmeldelink; unbestätigte Einträge löscht die Wartung nach 30 Tagen. Schutz: Herkunftsprüfung, Honeypot, Wiederversand frühestens nach 10 Minuten, höchstens 3 Mails je Adresse und Tag, höchstens 30 Einträge je Minute, identische Antworten gegen Adressermittlung.'],
            ['type' => 'Neu', 'text' => 'Adminbereich: Karte „Vormerkungen für angekündigte Integrationen“ mit Zählung je Anbieter (bestätigt, unbestätigt, abgemeldet) und den letzten 200 Einträgen. Datenschutzerklärung um Abschnitt 3a (Vormerkung, Einwilligung, Widerruf) ergänzt; Übersicht Integrationen und Hilfe angeglichen.'],
            ['type' => 'Geändert', 'text' => 'Empfehlung zur Produkttrennung in docs/integrations.md: eine Plattform, getrennte Anbindungen über die bestehende Adaptergrenze und getrennter Marktauftritt je Rechnungssystem, keine zweite Anwendung. Adversariale Prüfung (21 Agenten, 16 bestätigte Befunde) eingearbeitet: Abmeldelink in der Bestätigungsmail, Bestätigung und Abmeldung erst per Button, keine stille Bestätigung ohne Mailversand, Tagesgrenze 3 Mails je Adresse, Wettlauf beim ersten Eintrag abgefangen, Löschfristen im Code wie in der Datenschutzerklärung (unbestätigt, abgemeldet, nach Startnachricht je 30 Tage), Bereinigung auch im Cron-Pfad, Einwilligungsfassung v2 mit Archiv docs/einwilligungen.md, Adminaktionen Abmelden und Löschen mit 2FA und Audit. Test tools/interest-check.sh (69 Fälle gegen temporäre MariaDB).'],
         ]],
        ['version' => '4.17', 'date' => '07.09.2026', 'title' => 'Deployment übersteht Netzaussetzer, kein grüner Lauf ohne Auslieferung',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Ein einzelner Netzaussetzer beendete den gesamten Deployjob: Der erste SSH-Aufruf scheiterte mit "connect to host ... Connection timed out" (Exitcode 255), obwohl der Server in Ordnung war und dort nichts geschehen ist. Alle übertragenden Schritte und das Auslösen laufen jetzt über .github/scripts/vps-ssh-retry.sh mit bis zu vier Versuchen und wachsender Pause (5, 10, 20 s). Jeder Schritt ist idempotent (mkdir -p, rsync mit unveränderter Quelle), das Auslösen zusätzlich durch die serverseitige Sperre geschützt. rsync-Exitcode 24 gilt als Erfolg, dauerhafte rsync-Fehler werden nicht wiederholt.'],
            ['type' => 'Behoben', 'text' => 'Gefährlichste Lücke, gefunden bei der Prüfung dieses Fixes: Verlor der Auslöseschritt die Verbindung, konnte der Lauf GRÜN enden, obwohl nichts ausgeliefert wurde. Der Warteschritt sah den success des vorherigen Deployments, weil die Statusdatei jeden Lauf überlebt. Jetzt liefert .github/scripts/vps-trigger.sh drei Zustände (triggered, rejected, unclear; ein nie erreichter Server endet sofort als unreachable mit klarer Ursache statt zwölf Minuten zu warten), und der Warteschritt akzeptiert einen Endstatus nur, wenn er nach dem Start dieses Laufs geschrieben wurde. Andernfalls endet der Lauf mit "Kein Deployment dieses Laufs nachweisbar".'],
            ['type' => 'Behoben', 'text' => 'Ein abgebrochener rsync konnte ein halbes Release hinterlassen, das Candidate-Prüfung, Migration und Cutover durchlief; fehlte dabei die Datei einer Migration, meldete die Migration "0 offen" und neuer Code liefe auf altem Schema. Der Workflow schreibt jetzt nach der letzten Übertragung releases/<sha>/.release-complete (sha, Zeitstempel, Dateizahl), und deploy.sh verweigert Releases ohne diesen Nachweis (SMARTEINZUG_SKIP_RELEASE_CHECK=1 nur für bewussten Handbetrieb). rollback.sh verlangt ihn nicht, weil ältere Releases ihn nicht tragen, vermerkt sein Fehlen aber. Reste abgebrochener Läufe räumt die Bereinigung weg, damit sie keinen Rollback-Platz belegen.'],
            ['type' => 'Neu', 'text' => 'Fehlgeschlagene Statusabfragen werden im Workflow gemeldet (erste und jede sechste, mit Ursache), damit eine Zugangsstörung nicht wie ein hängendes Deployment aussieht; das Wartescript bricht mit klarer Meldung ab, wenn jq fehlt. Jeder Übertragungsschritt hat eine eigene Frist von 10 Minuten. Betriebsanleitung: docs/vps/06-betrieb.md, Abschnitte "SSH-Fehler des Deployments" (Prüfschritte zu Netz, Firewall, fail2ban, Hostkey), "Nachweis eines vollständigen Release" und "Kein grüner Lauf ohne Deployment".'],
            ['type' => 'Neu', 'text' => 'tools/github-ssh-retry-check.sh prüft die Wiederholung und das echte Auslöseskript gegen ein Fake-ssh (43 Fälle: Erfolg im ersten und dritten Versuch, begrenzte Versuchszahl, Verbindungs- gegen Fachfehler, endgültige Exitcodes, TRIGGERED nach fehlgeschlagenem Versuch, REJECTED mit eigenem und fremdem sha, unerreichbarer Server, Abbruch mitten in der Sitzung, Betriebsstandard der Pausen 5, 10, 20 s, gemischte Fehlerfolge, Argumentweitergabe). tools/github-poll-check.sh deckt zusätzlich die Frischeprüfung ab (25 Fälle), tools/redis-deploy-check.sh das unvollständige Release und die Bereinigung (109 Fälle).'],
         ]],
        ['version' => '4.16', 'date' => '07.09.2026', 'title' => 'Kennzahlen anklickbar, Statusseite mit echten Daten',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Die fünf Kennzahlen der Systemübersicht sind anklickbar und führen auf die Liste, aus der sie stammen. Neu ist der Abschnitt "Wartende Aufgaben" (System, Jobs): wartende Jobs mit Firma, Typ, einreichender Person (fehlt sie, war es der Scheduler), Zeitpunkt, nächstem Versuch, Versuchszahl und letztem Fehler; Reservierungen, deren Worker sich nicht mehr meldet, mit Laufzeit und Alter des Heartbeats; offene Synchronisationsläufe mit Fortschritt und Kennzeichnung "hängt"; fällige Einzüge samt Zustand des Einreichfensters und nächster Öffnung.'],
            ['type' => 'Neu', 'text' => 'Aktionen im Abschnitt "Wartende Aufgaben" (je mit 2FA-Code und Protokoll im Audit): "Jetzt ausführen" und "Abbrechen" für wartende Jobs, "Reservierung freigeben" für Jobs ohne Lebenszeichen des Workers (ohne Fehlversuch; bei frischem Heartbeat verweigert, damit einem laufenden Worker der Job nicht entzogen wird) und "Fortsetzung einreihen" für einen offenen Synchronisationslauf (setzt am Zwischenstand an, gesperrt bei pausierter Firma).'],
            ['type' => 'Behoben', 'text' => 'Die öffentliche Statusseite zeigte dauerhaft "Status unbekannt (Daten veraltet)". Ursache war der fehlende letzte Einrichtungsschritt: Die Anwendung hatte kein Ziel für die Statusdaten (status_publish leer), und im Release kann sie nicht schreiben. Jetzt schreibt sie nach /opt/smarteinzug/shared/status/status.json, Caddy liefert genau diese Datei unter dem Status-Host aus (die PHP-Container schreibend, Caddy nur lesend eingebunden; bewusst nicht shared/storage, dort liegen Kundendaten). deploy.sh legt den Ordner an und kopiert den Platzhalter einmalig hinein; veröffentlichte Daten überleben jedes Deployment. Zu setzen bleibt der Eintrag status_publish in shared/config.php (siehe docs/status-page.md).'],
            ['type' => 'Geändert', 'text' => 'Die Übersicht nennt Herkunft und Grenzen der Messwerte jetzt nach der tatsächlichen Lage statt pauschal "Vom Hosting nicht bereitgestellt": Je Messwert wird angezeigt, ob eine aktuelle Messung vorliegt (CPU, RAM, Systemlast, Festplatte und Sicherungen erfasst der Metrik-Sammler auf dem VPS). Technisch nicht erfassbar bleiben die Zahl belegter PHP-Prozesse und eine unabhängige Erreichbarkeitsprüfung von außen.'],
            ['type' => 'Neu', 'text' => 'tools/scheduler-sync-check.sh deckt zusätzlich die neuen Ansichten und Aktionen ab (35 Fälle gegen eine echte temporäre MariaDB): wartende gegen reservierte Jobs, Freigabe ohne Fehlversuch, Schutz bei frischem Heartbeat, offene Läufe mit und ohne Job sowie statisch die Verlinkung der Kennzahlen und die 2FA-Pflicht der Aktionen. tools/compose-check.py prüft den Weg der Statusdaten (Einbindungen, Caddyfile, Ordneranlage in deploy.sh, Vorlage in config.example.php), tools/redis-deploy-check.sh die einmalige Kopie des Platzhalters.'],
         ]],
        ['version' => '4.15', 'date' => '07.09.2026', 'title' => 'Abgebrochene Synchronisation wird sofort fortgesetzt',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Im Monitoring blieb nach einem hart beendeten Worker dauerhaft "Wartende Aufgaben (1 Sync)" stehen. Ursache: Der Scheduler schloss den verwaisten Lauf zwar als Fehler, reihte die Fortsetzung aber erst zur nächsten regulären Fälligkeit ein (auto_sync_hours, Vorgabe 6 Stunden). Jetzt wird die Fortsetzung sofort eingereiht; der Lauf setzt am gespeicherten Cursor an. Ein Doppeleintrag ist über den dedupe_key ausgeschlossen, eine pausierte Firma und ein Lauf mit Fortschritt bleiben unberührt.'],
            ['type' => 'Neu', 'text' => 'tools/scheduler-sync-check.sh prüft den automatischen Synchronisationsplan gegen eine echte temporäre MariaDB: verwaister Lauf wird geschlossen und sofort fortgesetzt, frischer Lauf bleibt unberührt, kein zweiter Job bei bereits vorhandenem, pausierte Firma unangetastet. Zusätzlich ist festgehalten, dass das Einreichfenster für Lastschriften (Vorgabe 23:00 bis 06:00) ausschließlich das Einreichen von Einzügen begrenzt: Synchronisation, Klärung unklarer Versuche, Monitoring und Statusabrufe laufen rund um die Uhr, und app/jobs.php prüft das Fenster nicht.'],
            ['type' => 'Geändert', 'text' => 'Der Prüfstand mit temporärer MariaDB liegt jetzt gemeinsam in tools/lib/mariadb-sandbox.sh und wird von tools/worker-signal-check.sh und tools/scheduler-sync-check.sh genutzt (ein Aufbau, ein Aufräumweg).'],
         ]],
        ['version' => '4.14', 'date' => '07.09.2026', 'title' => 'Einführungspreis mit rollierendem Stichtag',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'Der Einführungspreis des Tarifs UNLIMITED START gilt nicht mehr bis zum festen 31.12.2026, sondern für Firmenaccounts, die bis zum Ende des laufenden Kalendermonats angelegt werden; der Stichtag verschiebt sich damit von selbst (am 30.09. lautet er 30.09.2026, am 01.10. bereits 31.10.2026). Ein bereits angelegter Account behält seinen Preis unverändert, solange das Abonnement läuft. Grundlage bleibt die Tabelle plans, hier ist kein Preis hinterlegt.'],
            ['type' => 'Neu', 'text' => 'app/pricing.php berechnet den Stichtag (intro_price_deadline, intro_price_deadline_sentence) ohne Datenbank; das Hilfe-Center nennt den konkreten Tag, die statischen Marketingseiten (14 Seiten auf vier Domains, einschließlich AGB und FAQ) nennen die gleichlautende Regel ohne Datum, damit dort kein Datum von Hand gepflegt werden muss. Die FAQ-Frage "Was passiert nach dem 31.12.2026?" heißt jetzt "Was passiert, wenn der Einführungspreis endet?" und verweist auf den dann veröffentlichten Preis für neu angelegte Accounts.'],
            ['type' => 'Neu', 'text' => 'tools/pricing-check.php prüft den Stichtag über Monats-, Jahres- und Schaltjahresgrenzen, verbietet ein festes Ablaufdatum in Preisangaben (Muster "bis TT.MM.JJJJ angelegt/registriert" in HTML und PHP) und hält Marketingseiten und Anwendung auf derselben Aussage.'],
         ]],
        ['version' => '4.13', 'date' => '07.09.2026', 'title' => 'Betriebs- und Migrationsdokumentation im Adminbereich',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Die interne Betriebs- und Migrationsdokumentation der Müller Holding AG (Dokument-ID MHAG-SE-OPS-20260907, Version 1.0, 45 Kapitel mit Architektur, Containerinventar, Netzen, Deploymentablauf, Störungsanalysen, Backups, Runbooks und Entscheidungsregister) steht im Adminbereich unter System, Dokumentation zur Verfügung: als Kapitel der technischen Dokumentation (HTML und Sammel-PDF, mit Tabellen, Textdiagrammen und Befehlsblöcken) und zusätzlich als unveränderte Originalfassung im PDF. Auslieferung wie bisher ausschließlich über admin-doc.php an Plattformadministratoren, jeder Abruf im Audit.'],
            ['type' => 'Geändert', 'text' => 'tools/build-docs.py liefert neben der erzeugten Dokumentation auch unveränderte Originalunterlagen aus docs/anlagen/ aus und nennt sie im Manifest mit Titel; die Übersicht im Adminbereich zeigt eine Spalte Dokument und trennt damit Anlagen von der erzeugten Dokumentation.'],
            ['type' => 'Neu', 'text' => 'tools/docs-build-check.py prüft ohne Webserver, dass jede deklarierte Kapitelquelle und Anlage vorhanden ist, das Manifest zu den erzeugten Dateien passt (Name, Größe, ausgelieferter Dateityp), jede Anlage byteweise mit dem Original übereinstimmt und einen Titel trägt, jedes Kapitel im erzeugten HTML erscheint und admin-doc.php weiterhin Superadmin, Manifest-Allowlist, realpath-Prüfung und Audit erzwingt.'],
         ]],
        ['version' => '4.12', 'date' => '07.09.2026', 'title' => 'Plattform-Abrechnung: Inbetriebnahme prüfbar und wiederholbar',
         'entries' => [
            ['type' => 'Neu', 'text' => 'bin/billing-check.php prüft die Plattform-Abrechnung, ohne etwas zu ändern: Art und Betriebsart des Stripe-Schlüssels (live oder test, nur maskiert ausgegeben), Signaturgeheimnis, Basisadresse, Stripe-Konto und Einzugsfähigkeit, je buchbarem Tarif den hinterlegten Preis (Betrag, Währung, 28-Tage-Periode, Nettopreis über tax_behavior exclusive, Produkt nicht archiviert), den Webhook-Endpunkt samt der fünf benötigten Ereignisse, das Kundenportal, Stripe Tax sowie die Zahl der Firmen, die beim Scharfschalten gesperrt würden (mit Namen).'],
            ['type' => 'Neu', 'text' => 'bin/billing-setup-stripe.php legt Produkt und Preis je buchbarem Tarif in Stripe an und trägt die Preis-ID in die Tabelle plans ein. Betrag, Periode und Bezeichnung stammen ausschließlich aus plans. Standard ist ein Trockenlauf; die Anlage verlangt --apply, mit Live-Schlüssel zusätzlich --live-bestaetigt. Über den lookup_key lexsepa_<tarifcode> erkennt der wiederholte Aufruf einen vorhandenen Preis und legt keinen zweiten an; passt ein vorhandener Preis nicht zum Tarif, wird die Preis-ID nicht eingetragen.'],
            ['type' => 'Behoben', 'text' => 'Die beiden Werkzeuge der Abrechnung verwendeten billing_client(), das zusätzlich billing.enabled verlangt: In der Produktion sprangen damit genau vor dem Scharfschalten alle Stripe-Prüfungen (Konto, Preise, Webhook, Kundenportal, Steuer) mit der Meldung "nicht konfiguriert" aus, und die Anlage der Artikel wäre gar nicht möglich gewesen. Sie nutzen jetzt billing_setup_client(): unabhängig vom Schalter, sobald ein brauchbarer Geheimschlüssel vorliegt, weiterhin nur lesend in bin/billing-check.php. Die Anwendung selbst rechnet ohne billing.enabled unverändert nichts ab.'],
            ['type' => 'Neu', 'text' => 'docs/abrechnung.md: Anleitung zum Scharfschalten in sieben Schritten (zuerst Testschlüssel, Stripe Tax und Kundenportal, Anlage der Artikel, Webhook, vollständiger Testdurchlauf, Schutz bestehender Firmen über billing_exempt, dann live), mit Rücknahmeweg und Hinweisen für den laufenden Betrieb.'],
            ['type' => 'Neu', 'text' => 'tools/billing-setup-check.php prüft die Logik ohne Stripe-Konto, ohne Netz und ohne Datenbank (55 Fälle): abweichender Betrag, falsche Währung, archivierter Preis, Bruttopreis statt Nettopreis, Monatsintervall statt 28 Tage, Verbrauchs- und Einmalpreis, fehlende oder deaktivierte Webhook-Endpunkte, fehlende Ereignisse, unvollständige Konfiguration, Maskierung der Schlüssel sowie der Abgleich, dass app/billing.php genau die geprüften Ereignisse verarbeitet.'],
         ]],
        ['version' => '4.11', 'date' => '07.09.2026', 'title' => 'Deploymentstatus sichtbar, Worker-Shutdown in Sekunden statt 11 Minuten',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'GitHub meldete fälschlich eine Zeitüberschreitung, obwohl der serverseitige Deploy lief und erfolgreich endete: deploy-status.sh lieferte durchgehend "phase: unknown". Ursache: deploy.sh (und rollback.sh) übernehmen deploy/vps per rsync --delete nach /opt/smarteinzug/deploy und schlossen die Laufzeitdateien .deploy-status.json und .deploy.pid nicht aus; die vom Deploy-Runner Sekunden zuvor geschriebene Statusdatei wurde gelöscht und erst nach dem Ende neu geschrieben. Die Excludes umfassen jetzt alle Laufzeitdateien (/.deploy*, /.release*, /.previous_sha, /.php-image.sha256, /.env); deploy.sh trägt zusätzlich den aktuellen Schritt atomar in die Statusdatei ein (Feld step), das GitHub-Polling zeigt jeden Phasen-/Schrittwechsel.'],
            ['type' => 'Behoben', 'text' => 'Scheduler- und Worker-Container brauchten beim Deployment bis zu 11 Minuten ("Container failed to exit within 11m0s of signal 3"). Ursache: Das Basisimage php:8.4-fpm-alpine setzt STOPSIGNAL SIGQUIT; Worker und Scheduler behandelten nur SIGTERM/SIGINT, und ein PID-1-Prozess ohne Handler bekommt das Signal vom Kernel verworfen; stop_grace_period 660 s ließ Docker dann 11 Minuten warten, und deploy.sh startete die Worker danach nochmals mit derselben Frist neu. Jetzt: stop_signal SIGTERM und stop_grace_period 75 s für Scheduler/Worker (20 s für den Metrik-Sammler), php läuft direkt als PID 1 (kein sh -c), die Prozesse behandeln SIGTERM, SIGINT und SIGQUIT.'],
            ['type' => 'Neu', 'text' => 'Kontrollierter Worker-Shutdown (app/worker_signals.php): Nach dem Stop-Signal wird kein neuer Job mehr angenommen; ein laufender Job endet am nächsten kooperativen Abbruchpunkt (Synchronisation nach jedem Schritt, Einzüge zwischen zwei Einzügen) als Fortsetzung ohne Fehlversuch; für unterbrechbare Jobtypen zieht nach 30 s eine Notbremse (SIGALRM, kontrollierte Fortsetzung). Geldbewegende Jobs (Einzüge, unklare Versuche) werden nie mitten im Ablauf unterbrochen. Ein dennoch hart beendeter Job wird nach heartbeat_ttl automatisch wieder freigegeben. Offene Datenbanktransaktionen werden vor der Statusänderung zurückgerollt.'],
            ['type' => 'Geändert', 'text' => 'Kein zweiter Neustart von Scheduler/Workern nach dem Cutover mehr: working_dir ist Teil des Compose-Konfigurations-Hash, "up -d" erzeugt die Container bei jedem Releasewechsel zwingend neu. Statt des Neustarts verifiziert deploy.sh (und rollback.sh) per docker inspect, dass jeder PHP-Container läuft und das neue Release als working_dir trägt; bei Abweichung Rollback. Typische Deploymentdauer damit wenige Minuten statt über 20.'],
            ['type' => 'Geändert', 'text' => 'Redis-Infrastruktur: Neben redis.conf löst jetzt auch eine geänderte Compose-Definition des redis-Dienstes (Konfigurations-Hash, z. B. neuer Alias) die kontrollierte Aktualisierung vor der Candidate-Prüfung aus; die Gesundheitsprüfung verlangt mindestens einen Container mit Health "healthy" (leere Ausgabe gilt nicht mehr als gesund). Redis-Diagnose: IPv6-Adressen und Unix-Sockets korrekt, CIDR-Prüfung lehnt ungültige Angaben ab, Lese-Timeout 1,5 s, DIAGNOSE-Zeile auch bei Erfolg, Kategorien loading/busy/protocol, Circuit Breaker berücksichtigt protocol/connection_refused.'],
            ['type' => 'Neu', 'text' => 'GitHub-Polling in .github/scripts/vps-wait-status.sh ausgelagert (Frist unverändert 12 Minuten, Phase/Schritt protokolliert, Hinweis auf deploy-status.sh --tail bei Zeitüberschreitung). Regressionstests: tools/deploy-runner-check.sh (echte deploy.sh unter dem Runner: Status sofort running, überlebt den rsync, gültiges JSON bei jeder Abfrage, success/failed, --tail, keine Geheimnisse), tools/github-poll-check.sh (running/success/failed/unknown/SSH-Abbruch/sha-Abweichung/Frist), tools/worker-signal-check.sh (echte PHP-Prozesse und echte bin/worker.php gegen eine temporäre MariaDB: Stop-Signale, kein neuer Job, Notbremse, Geldfluss-Jobs unangetastet, Queue-Semantik), tools/compose-check.py (stop_signal, Grace-Period, php als PID 1, rsync-Excludes, kein restart -t), tools/redis-deploy-check.sh (16 Szenarien der Redis- und Cutover-Logik gegen einen Fake-docker, darunter der Vorab-Stopp veralteter Container und der Ausweichweg ohne "stop --signal").'],
            ['type' => 'Behoben', 'text' => 'Adversariale Prüfung des Signalmodells: Die Notbremse bei einer laufenden Synchronisation wurde durch catch-Throwable-Schichten (sync_state_step, job_sync_run) in einen Fehlversuch mit Backoff (bis zu 1 h) und einen sichtbaren last_error umgedeutet. Jetzt reichen diese Stellen die WorkerShutdownException durch (sync_state_step gibt nur die Sperre frei, kein fehlgeschlagener Lauf), und job_execute() bestimmt die Ergebnisklasse zentral über worker_job_exception_outcome(): Nach einer ausgelösten Notbremse zählt jede Ausnahme des Jobs als Fortsetzung ohne Fehlversuch. Wartung reicht die Notbremse zwischen Teilaufgaben durch, mail_send_direct wertet sie nicht als Transportfehler.'],
            ['type' => 'Behoben', 'text' => 'Erstes Deployment ab 4.11 hätte nochmals 11 Minuten gedauert: Docker stoppt einen Container beim Neuerzeugen mit der Stop-Konfiguration des laufenden Containers (SIGQUIT, 660 s bei allen Containern bis 4.10). deploy.sh prüft vor dem Cutover per docker inspect StopSignal/StopTimeout der Hintergrund-Container und beendet veraltete vorab gezielt mit docker stop --signal SIGTERM --timeout 90 (idempotent, danach wirkungslos; greift erneut nach einem Rollback auf ein älteres Release; "stop --signal" gibt es erst ab Docker CLI 23, deploy.sh fragt die Fähigkeit selbst ab und weicht sonst auf "kill --signal SIGTERM" plus Warten und einen regulären Stopp mit kurzer Frist aus, eine Versionsprüfung von Hand ist nicht nötig).'],
            ['type' => 'Behoben', 'text' => 'Statusdatei: deploy-status.sh --tail fand während des Laufs die Protokolldatei nicht (deploy_step formatierte per jq mehrzeilig, das sed-Muster erwartete das kompakte Format); jetzt jq -c und eine formatunabhängige Auswertung. deploy-runner.sh belegt die Statusdatei bereits im Vordergrund unter der Sperre mit running und dem neuen sha vor, damit das GitHub-Polling nie das Ergebnis des vorherigen Laufs (alter sha, alter Fehlstatus) als aktuelles Ergebnis liest.'],
            ['type' => 'Behoben', 'text' => 'deploy.sh/rollback.sh: Zuweisungen mit Compose-Pipelines (config --hash, ps -q, config --images) beendeten das Skript unter set -euo pipefail bei einem Fehler des Docker-CLI still, ohne Meldung und ohne Rollback, auch in der Bindungsprüfung nach dem Cutover; jetzt || true mit regulärer Fehlerbehandlung. deploy_step() kann das Deployment nicht mehr durch ein fehlgeschlagenes mv beenden. rollback.sh prüft --expect-env und den Migrationsstand in einem isolierten Wegwerfcontainer, wenn der php-Container nicht läuft (automatischer Rollback aus der Bindungsprüfung). Die Verifikation der Release-Bindung liegt vor der Aktivierung des Symlinks current (bei verweigertem Rollback zeigt die Buchführung weiter auf das letzte gute Release). Meldung des Redis-Rückbaus ehrlich, wenn nur die Compose-Definition geändert war.'],
            ['type' => 'Geändert', 'text' => 'Signalmodell nachgeschärft: unclear_attempts erhält kooperative Abbruchpunkte (zwischen Firmen und vor jedem Stripe-Aufruf) und endet damit innerhalb der Grace-Period; mail ist nicht mehr erzwungen unterbrechbar (SMTP-Dialog zwischen Annahme und Rückkehr); Wartung prüft das Stop-Signal zwischen Teilaufgaben; Signalhandler werden vor dem ersten Datenbankzugriff installiert (kein verworfenes SIGTERM während eines blockierten Verbindungsaufbaus); WORKER_STOP_JOB_SECONDS ist auf 30 begrenzt; Herleitung der 75 s ehrlich als Normalfall dokumentiert, heartbeat_ttl-Spanne korrigiert (120 bis 1800 s). Ein Einzugsjob, den das Stop-Signal vor dem ersten Einzug trifft, wird als Fortsetzung eingeplant statt als erledigt gemeldet.'],
            ['type' => 'Geändert', 'text' => 'Regressionstests erweitert: worker-signal-check.sh beendet die temporäre MariaDB zuverlässig (zuvor blieb je Lauf ein Prozess zurück) und prüft die Ergebnisklasse nach umgedeuteter Notbremse sowie den Schutz von mail; redis-deploy-check.sh prüft Redis, das nie healthy wird oder ohne Container erscheint, den Vorab-Stopp veralteter Container und den ehrlichen Rückbau-Hinweis; deploy-runner-check.sh prüft --tail während des Laufs und die Vorbelegung gegen einen veralteten Status; Sandbox-Verzeichnisse werden auch bei Abbruch aufgeräumt.'],
         ]],
        ['version' => '4.10', 'date' => '07.09.2026', 'title' => 'Root Cause Redis: Alias-Kollision mit Coolifys eigenem Redis',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Der Hostname "redis" war auf dem Coolify-Server mehrdeutig: Coolifys eigener Stack führt einen Dienst "redis" (Container coolify-redis, mit Passwort) im gemeinsam genutzten Netz "coolify", an dem unsere PHP-Container für Datenbank und Internet hängen. Dockers eingebetteter DNS liefert den Alias aus dem Netz ohne internal: true zuerst, also Coolifys Redis; der erste Befehl erhielt "NOAUTH Authentication required" (gemeldet als "redis: other" mit alten bzw. "redis: auth" mit neuen Kategorien), obwohl unser Redis kein Passwort verlangt. Aus Primärquellen (Coolify-Compose-Dateien, Docker-Engine-Quelltext) belegt und lokal gegen einen echten passwortgeschützten Redis nachgestellt. Unser Redis trägt jetzt den eindeutigen Alias "smarteinzug-redis" (nur im internen Netz); alle PHP-Dienste erhalten SMARTEINZUG_REDIS_HOST und SMARTEINZUG_REDIS_EXPECTED_CIDR aus dem Stack, app/redis.php bevorzugt diese Variable vor config.php. shared/config.php muss nicht geändert werden. protected-mode no (Version 4.8) bleibt als Behebung eines zweiten, latenten Fehlers bestehen.'],
            ['type' => 'Geändert', 'text' => 'bin/healthcheck.php --redis diagnostiziert stufenweise (Auflösung, erwartetes Netz, TCP, Redis-Protokoll) und meldet statt "other" eine konkrete Kategorie: alias_missing, dns, network_mismatch, alias_ambiguous, connection_refused, timeout, network_unreachable, redis_protected_mode, auth, protocol. Bei einem Fehlschlag steht eine DIAGNOSE-Zeile (Host, aufgelöste Adressen, erwartetes Netz, Stufe, Kategorie, gekürzte Originalmeldung, Passwörter maskiert) im Deployment-Protokoll. Nur transiente Stufen werden wiederholt.'],
            ['type' => 'Geändert', 'text' => 'deploy.sh führt den netzwerkbasierten Redis-Test immer mit dem Code des neuen Release aus (nur er kennt den eindeutigen Hostnamen). Der Rollback der Redis-Infrastruktur wird getrennt bewertet: technische Wiederherstellung (redis.conf zurück, Dienst neu erzeugt, healthy) als harte Kriterien, der Netzwerktest gegen den alten Zustand nur als Warnung, da der alte Zustand bekanntermaßen scheitern kann.'],
            ['type' => 'Neu', 'text' => 'Regressionstests: tools/healthcheck-redis-check.php stellt die Alias-Kollision gegen einen echten passwortgeschützten Redis nach (auth, NOAUTH, kein Passwort in der Ausgabe) und prüft network_mismatch, alias_missing sowie den Vorrang von SMARTEINZUG_REDIS_HOST; tools/staging-isolation-check.py bestätigt Alias, Stack-Variablen und gemeinsames internes Netz für Produktion und Staging; tools/redis-deploy-check.sh prüft fehlenden Alias mit technisch erfolgreichem Rollback auf den alten Zustand, Netzwerktest mit dem neuen Release, dasselbe Compose-Projekt für alle Aufrufe, --no-deps und die Reihenfolge Recreate, Netzwerktest, Candidate, Migration, Cutover.'],
         ]],
        ['version' => '4.9', 'date' => '07.09.2026', 'title' => 'Redis-Infrastruktur deploybar machen (Bootstrap-Problem behoben)',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Der Redis-protected-mode-Fix (Version 4.8) konnte sich nicht selbst deployen: Die Candidate-Prüfung kommuniziert mit dem bereits laufenden redis-Dienst, der aber wegen des Bind-Mounts von redis.conf nicht automatisch neu erzeugt wird, nur weil sich der Dateiinhalt geändert hat. Der Candidate mit neuem Code prüfte deshalb weiterhin gegen den alten, unveränderten Redis-Container. deploy.sh stellt jetzt vor der Candidate-Prüfung fest, ob sich redis.conf gegenüber dem laufenden Release geändert hat: unverändert bleibt Redis unberührt; geändert wird ausschließlich der redis-Dienst vorab validiert, gezielt neu erzeugt (kein anderer Dienst betroffen), auf healthy geprüft und die Erreichbarkeit aus einem ANDEREN Container über das interne Netz bestätigt (nicht per "docker exec redis redis-cli ping", das genau das protected-mode-Problem verborgen hatte) - erst danach beginnt die eigentliche Candidate-Prüfung.'],
            ['type' => 'Neu', 'text' => 'Schlägt die Redis-Aktualisierung fehl (ungültige Konfiguration, Recreate schlägt fehl, nicht healthy, oder healthy aber über das Netz blockiert), wird ausschließlich die Redis-Infrastruktur auf die vorherige Konfiguration zurückgesetzt und deren Erreichbarkeit erneut bestätigt; das Deployment bricht danach ab, ohne Migration und ohne Cutover, die übrige laufende Anwendung bleibt unverändert.'],
            ['type' => 'Neu', 'text' => 'Vor jeder Redis-Änderung wird zusätzlich geprüft, dass Redis keinen veröffentlichten Host-Port hat, ausschließlich am internen Netz smarteinzug_internal hängt (nicht am öffentlichen Coolify-Netz) und keine Traefik-Labels trägt - Voraussetzung dafür, dass protected-mode no vertretbar bleibt; verletzt eine dieser Bedingungen, bricht das Deployment ab, bevor irgendetwas an Redis geändert wird.'],
            ['type' => 'Neu', 'text' => 'Regressionstest tools/redis-deploy-check.sh (kein Docker-Daemon nötig): simuliert /opt/smarteinzug mit einem steuerbaren Fake-"docker", gegen den die tatsächliche deploy.sh unverändert läuft; bestätigt u. a. kein Recreate bei unveränderter redis.conf, kontrollierte Aktualisierung vor der Candidate-Prüfung bei geänderter redis.conf, Abbruch mit bestätigtem Rollback bei über das Netz blockiertem Redis, Erkennung einer ungültigen Konfiguration bereits in der Vorab-Validierung, Abbruch bei verletzten Netzwerk-Isolationsvorgaben, Idempotenz bei Wiederholung. tools/staging-isolation-check.py bestätigt zusätzlich die Redis-Netzwerk-Isolation in Produktion und Staging.'],
         ]],
        ['version' => '4.8', 'date' => '07.09.2026', 'title' => 'Tatsächliche Ursache des Redis-Fehlschlags: protected mode',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Die Candidate-Prüfung meldete weiterhin einen Redis-Fehlschlag ("redis: auth" bzw. zuvor "redis: other"), obwohl config.php korrekt kein Passwort und redis.conf kein requirepass enthielt und "docker exec smarteinzug-redis-1 redis-cli ping" PONG lieferte. Tatsächliche, durch einen echten temporären Redis-Server bestätigte Ursache: redis.conf setzte protected-mode yes ohne Passwort; in dieser Kombination lehnt Redis jeden Befehl (nicht die TCP-Verbindung) eines NICHT über Loopback verbindenden Clients ab, also jeden Zugriff aus einem anderen Container. "docker exec ... redis-cli ping" lief dagegen selbst über Loopback und täuschte deshalb Gesundheit vor, die für keinen anderen Container galt. redis.conf setzt jetzt protected-mode no (sicher, da Redis ohnehin nur im internen, nicht öffentlich erreichbaren Docker-Netz erreichbar ist).'],
            ['type' => 'Geändert', 'text' => 'monitor_category() erkennt die Redis-protected-mode-Meldung als eigene Kategorie redis_protected_mode statt sie fälschlich als auth (falsches Passwort in der eigenen Konfiguration vermutet, was hier nie die Ursache war) oder other zu melden.'],
            ['type' => 'Neu', 'text' => 'Regressionstest tools/healthcheck-redis-check.php erweitert: startet testweise einen echten, temporären Redis-Server (protected-mode yes/no) und prüft den Zugriff über eine echte, nicht-Loopback-Adresse dieses Hosts; bestätigt sowohl die neue Diagnosekategorie als auch, dass protected-mode no den Zugriff tatsächlich ermöglicht, sowie eine statische Prüfung, dass redis.conf protected-mode no enthält.'],
         ]],
        ['version' => '4.7', 'date' => '07.09.2026', 'title' => 'Staging- und Produktionsisolation im VPS-Stack',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Eine Prüfung auf dem produktiven VPS (nur docker compose config, kein Start) ergab, dass Staging und Produktion denselben Compose-Projektnamen erbten und dadurch dieselben Container-, Netz- und Volume-Namen erhalten hätten (z. B. "smarteinzug_smarteinzug_internal", "smarteinzug_caddy_data"); zusätzlich verwendeten beide Umgebungen identische Traefik-Router-/Middleware-/Dienstnamen. docker-compose.staging.yml setzt jetzt einen eigenen Projektnamen ("smarteinzug-staging") und eigene Traefik-Namen ("smarteinzug-staging-*"); die Traefik-Labels von Produktion stehen dafür nicht mehr in der gemeinsamen docker-compose.yml, sondern ausschließlich in docker-compose.prod.yml.'],
            ['type' => 'Neu', 'text' => 'Zusätzliches technisches Sicherheitsnetz gegen einen versehentlichen Staging-Deploy oder -Rollback gegen die Produktionskonfiguration: shared/config.php erhält ein Feld "environment" (prod/staging, siehe app/config.example.php); die isolierte Candidate-Prüfung jedes Deployments und jeder Rollback rufen bin/healthcheck.php --expect-env=$DEPLOY_ENV auf und brechen ab, bevor Migrationen oder ein Cutover stattfinden, wenn die Konfiguration nicht zur erwarteten Umgebung passt (ein Staging-Aufruf verlangt das Feld zwingend). Zusätzlich prüft dieser Schritt, dass die Plattform-Abrechnung in Staging keinen Live-Stripe-Schlüssel verwendet.'],
            ['type' => 'Geändert', 'text' => 'Die primäre Absicherung bleibt die Servertrennung (Staging auf einem eigenen, physisch getrennten VPS mit eigener Coolify-MariaDB, niemals auf dem Produktions-VPS); die sichere Vorgehensweise zur Ersteinrichtung ist in docs/vps/02-einrichtung-vps.md, Kapitel 25, dokumentiert.'],
            ['type' => 'Neu', 'text' => 'Regressionstest tools/staging-isolation-check.py (kein Docker-Daemon nötig, nur docker compose ... config): bestätigt getrennte Projekt-/Volume-/Netz-/Traefik-Namen zwischen Produktion und Staging sowie das Vorhandensein des --expect-env-Schutzes in bin/healthcheck.php, deploy.sh und rollback.sh.'],
         ]],
        ['version' => '4.6', 'date' => '07.09.2026', 'title' => 'Verwertbare Fehlerdiagnose der Candidate-Prüfung',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Der erste produktive Einsatz der neuen Candidate-Prüfung (Version 4.5) scheiterte mit der unbrauchbaren Meldung "redis: other": Der Fehlertext eines fehlgeschlagenen Redis-Zugriffs im Alpine/musl-basierten PHP-Image wich von der bisher erkannten glibc-Formulierung ab und wurde nicht erkannt. bin/healthcheck.php --redis erkennt jetzt zusätzliche Fehlerklassen (DNS, Verbindung abgelehnt, Authentifizierung, vom Server beendete Verbindung) und versucht bei einem Fehlschlag bis zu dreimal mit kurzer Pause erneut, um eine rein transiente Störung beim Netzwerkaufbau eines frisch erzeugten Containers abzufedern.'],
            ['type' => 'Geändert', 'text' => 'deploy.sh meldet bei einem Fehlschlag der Candidate-Prüfung, der Migration, des Warteschritts auf gesunde Container oder des Health-Checks nach der Aktivierung zusätzlich Phase, fehlgeschlagenen Befehl, Exitcode, Release-SHA und den aktuellen Containerzustand in die persistente Logdatei, ohne jemals Zugangsdaten auszugeben. Die Reihenfolge Candidate-Prüfung vor Migration vor Cutover aus Version 4.5 bleibt unverändert bestehen; es wurde nichts an der bereits funktionierenden serverseitigen Entkopplung zurückgebaut.'],
            ['type' => 'Neu', 'text' => 'Regressionstest tools/healthcheck-redis-check.php: prüft monitor_category() gegen glibc- und musl-typische Fehlertexte, sowie bin/healthcheck.php --redis gegen einen nicht auflösbaren Hostnamen und einen geschlossenen Port; tools/compose-check.py bestätigt zusätzlich statisch, dass deploy.sh die Reihenfolge Candidate-Prüfung, Migration, Cutover einhält und beide isolierten Schritte ausschließlich über "docker compose run --rm --no-deps" laufen, ohne laufende Container anzufassen.'],
         ]],
        ['version' => '4.5', 'date' => '07.09.2026', 'title' => 'Ausfallsicheres VPS-Deployment, Release-Bindung ohne Symlink',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Ein VPS-Deployment brach ab, wenn die SSH-Verbindung des GitHub-Workflows waehrend des mehrminuetigen Container-Neustarts kurz abriss ("client_loop: send disconnect: Broken pipe"); Container blieben im Zustand "created" haengen. Das Deployment laeuft jetzt serverseitig entkoppelt (deploy/vps/scripts/deploy-runner.sh, setsid) und uebersteht einen SSH-Abbruch; der Workflow fragt den Fortschritt ueber kurze, unabhaengige Verbindungen ab.'],
            ['type' => 'Geändert', 'text' => 'working_dir aller Container und Caddys Dokumentenstamm sind jetzt an die Umgebungsvariable RELEASE_SHA gebunden (Pflichtwert), nicht mehr an den mutable Symlink "releases/current". Damit gehoeren Compose-Konfiguration, Healthchecks und Anwendungscode bei jedem Containerstart garantiert zum selben Release.'],
            ['type' => 'Geändert', 'text' => 'Datenbankmigrationen laufen jetzt in einem isolierten, zusaetzlichen Container mit dem neuen Code, BEVOR die laufenden Container angefasst werden (Candidate-Pruefung, dann Migration, dann Cutover). Schlagen Candidate-Pruefung oder Migration fehl, bleiben die laufenden Container unveraendert, ein Rollback ist dann nicht noetig.'],
            ['type' => 'Neu', 'text' => 'Regressionstests tools/compose-check.py (Release-Bindung als Pflichtwert, keine Datenbank-/Backup-Dienste im Stack) und tools/deploy-runner-check.sh (uebersteht simulierten SSH-Abbruch, lehnt parallele Deployments ab, idempotent).'],
         ]],
        ['version' => '4.4', 'date' => '06.09.2026', 'title' => 'Healthcheck des Metrik-Sammlers',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Der Container des Metrik-Sammlers galt auf dem VPS dauerhaft als ungesund und brach das Deployment ab, weil er den Healthcheck der Worker erbte, aber keinen Worker-Heartbeat schreibt. Er hat jetzt einen eigenen Healthcheck (bin/healthcheck.php --metrics: Prozessprüfung und eigenes Lebenszeichen der Sammelschleife).'],
            ['type' => 'Geändert', 'text' => 'Das PHP-Image gibt keinen Standard-Healthcheck mehr vor; jeder Dienst legt seinen passenden Healthcheck selbst fest. Eine automatische Prüfung (tools/compose-check.py) verhindert künftig, dass ein Dienst einen unpassenden Healthcheck erbt oder ein Dollarzeichen in einem Healthcheck falsch ausgewertet wird.'],
            ['type' => 'Geändert', 'text' => 'Die Servereinrichtung setzt die von Redis empfohlene Kernel-Einstellung vm.overcommit_memory dauerhaft und wiederholbar.'],
            ['type' => 'Behoben', 'text' => 'Datum von SEPA-Mandaten und die Prüfung überfälliger Termine richten sich nach der Zeitzone der Anwendung statt nach dem Datum des Datenbankservers. Läuft die Datenbank in UTC, trug ein zwischen Mitternacht und 02:00 Uhr digital erteiltes Mandat bisher das Datum des Vortages.'],
         ]],
        ['version' => '4.3', 'date' => '06.09.2026', 'title' => 'VPS-Stack nutzt die Coolify-Datenbank',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'Der Docker-Stack auf dem Hostinger-VPS startet keine eigene MariaDB und keinen eigenen Backup-Container mehr; genutzt wird die bereits eingerichtete private Coolify-MariaDB 11.8 (kein öffentlicher Port), gesichert durch Coolify mit externem Ziel Hetzner Object Storage.'],
            ['type' => 'Geändert', 'text' => 'PHP, Scheduler, Worker und Metrik-Sammler erreichen die Datenbank über das Coolify-Netz unter dem Containernamen; der Metrik-Sammler meldet die neueste lokale Coolify-Sicherung an das Monitoring (Komponente Sicherungen).'],
         ]],
        ['version' => '4.2', 'date' => '06.09.2026', 'title' => 'Ratenbegrenzung je Firma',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'Die zentrale Ratenbegrenzung für Lexware Office und Stripe zählt je API-Schlüssel (also je Firma) statt über alle Firmen zusammen; zusätzlich eine konfigurierbare Obergrenze insgesamt. Der Durchsatz wächst damit mit der Zahl der Worker.'],
            ['type' => 'Behoben', 'text' => 'Ein Rate-Limit einer einzelnen Firma öffnet nicht mehr den Circuit Breaker des Anbieters; der Breaker reagiert nur noch auf echte Störungen (Verbindungsfehler, Serverfehler).'],
         ]],
        ['version' => '4.1', 'date' => '06.09.2026', 'title' => 'Tarifwechsel, Upsell und Hostinger-VPS',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Tarifwechsel durch den Inhaber unter Firma > Abonnement (Upgrade sofort mit anteiliger Berechnung, Downgrade mit Gutschrift, Downgrade-Schutz für Benutzer), Bestellbestätigung und Protokoll wie beim Abschluss (Migration 019).'],
            ['type' => 'Neu', 'text' => 'Upsell bei erreichten Grenzen: Hinweis auf den nächsthöheren Tarif beim Benutzerlimit, ab 80 Prozent und bei ausgeschöpftem Einzugskontingent, einmal je Periode auch per E-Mail an den Inhaber. Erscheint nur, wenn mindestens zwei Tarife aktiv sind.'],
            ['type' => 'Geändert', 'text' => 'VPS-Stack auf Hostinger KVM 8 mit Coolify ausgerichtet: TLS am Coolify-Proxy, Caddy als interner HTTP-Server, Ressourcenlimits für 8 vCPU und 32 GB, Einrichtungsanleitung Kapitel 08.'],
         ]],
        ['version' => '4.0', 'date' => '06.09.2026', 'title' => 'Hintergrundverarbeitung und VPS-Migration vorbereitet',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Zentrale Job-Queue mit Prioritäten, Wiederholungen mit gestaffeltem Backoff, Dead-Letter-Ansicht im Admin, Worker mit Heartbeat, Scheduler, Circuit Breaker je Anbindung (Migration 018).'],
            ['type' => 'Neu', 'text' => 'Synchronisationshistorie je Firma mit Details (Dauer, Mengen, API-Aufrufe, Fehler) und Live-Fortschritt.'],
            ['type' => 'Neu', 'text' => 'E-Mail-Versand über die Warteschlange, Wartungsmodus je Firma für die Synchronisation, Feature-Flags je Firma.'],
            ['type' => 'Neu', 'text' => 'Strukturiertes Logging mit Correlation-ID über Webanfrage, Job, Worker und Audit.'],
            ['type' => 'Neu', 'text' => 'Docker-Stack für den IONOS VPS (Caddy, PHP-FPM, Worker, Scheduler, MariaDB, Redis, Backup, Host-Metriken), Deployment über SSH mit Rollback, Staging-Konfiguration.'],
            ['type' => 'Neu', 'text' => 'Adminbereich System: Reiter Jobs, Server, Versionen, Dokumentation; technische Dokumentation mit Diagrammen als PDF.'],
            ['type' => 'Geändert', 'text' => 'Bestehende Cron-Verarbeitung bleibt auf dem Webhosting erhalten; die Queue ist dort standardmäßig ausgeschaltet.'],
            ['type' => 'Behoben', 'text' => 'Adversariale Abnahme: X-Forwarded-For wird von rechts ausgewertet und validiert; Wartungsmodus und Adminhost-Trennung richten sich nach dem ausgeführten Skript, nicht nach der URL; Wartungsmodus pausiert Scheduler und Worker; Correlation-ID nur von vertrauenswürdigen Proxys.'],
            ['type' => 'Behoben', 'text' => 'Ratenbegrenzung reserviert Kontingent im Zielfenster; Maskierung von Webhook- und API-Schlüsseln in Protokollen; keine Empfängeradressen im Fehlerprotokoll; fehlgeschlagene Mail-Jobs ohne Nachrichteninhalt.'],
            ['type' => 'Behoben', 'text' => 'Container sehen nur Releases, Konfiguration und Speicher (kein Wurzeldateisystem, kein deploy/.env); Rollback prüft die Verträglichkeit mit dem Migrationsstand; kontrolliertes Beenden laufender Jobs beim Deployment (660 s).'],
         ]],
        ['version' => '3.4', 'date' => '06.09.2026', 'title' => 'Gerätefreigabe, Systemmonitoring, Statusseite',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Zwei-Faktor: Gerät für 90 Tage merken mit fester Gültigkeit, Verwaltung unter Sicherheit, Widerruf bei Passwort- und 2FA-Änderungen (Migration 016).'],
            ['type' => 'Neu', 'text' => 'Adminbereich System mit ehrlichen Messwerten, Zeitfenstern, Verfügbarkeit und Störungsverwaltung (Migration 017).'],
            ['type' => 'Neu', 'text' => 'Öffentliche Statusseite vorbereitet (status.smart-einzug.de), Snapshot mit Positivliste.'],
         ]],
        ['version' => '3.3', 'date' => '06.09.2026', 'title' => 'Multiaccount und Registrierung',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Multiaccount-Schalter im Profil, Registrierung mit bereits bekannter E-Mail-Adresse, Dublettenprüfung mit Sperren (Migration 015).'],
         ]],
        ['version' => '3.2', 'date' => '06.09.2026', 'title' => 'Navigation bereinigt',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'Kopfbereich ohne Dubletten zum Profilmenü, Team wird Firmendaten, Firmen wird Firmenübersicht, Exportbutton geprüft.'],
         ]],
        ['version' => '3.1', 'date' => '06.09.2026', 'title' => 'Synchronisierung gegen Doppelstarts',
         'entries' => [
            ['type' => 'Behoben', 'text' => 'Sperre mit Inhaber je Schritt, Zähler übersprungener Doppelstarts, API-Aufrufbudget je Schritt, Backoff mit Retry-After (Migration 014).'],
         ]],
        ['version' => '3.0', 'date' => '06.09.2026', 'title' => 'Abgesicherter Migrationsaufruf durch GitHub',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'migrate.php nur per POST mit Header X-Migration-Token, gemeinsame Sperre, Fehler werden nie automatisch wiederholt, Cron migriert nicht mehr.'],
            ['type' => 'Neu', 'text' => 'Abonnement vorbereitet: Bestellbestätigung mit AGB-Zustimmung, Rechnungsarchiv aus Stripe.'],
         ]],
        ['version' => '2.4', 'date' => '06.09.2026', 'title' => 'Synchronisation beschleunigt',
         'entries' => [
            ['type' => 'Geändert', 'text' => 'Änderungserkennung über updatedDate, seltenere Kontaktabrufe, zeitbasierte Schritte, Messwerte (Migration 013).'],
         ]],
        ['version' => '2.3', 'date' => '06.09.2026', 'title' => 'Hilfe-Center',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Anleitungen, häufige Fragen und Support-Anfragen mit Tickets (Migration 012).'],
         ]],
        ['version' => '2.2', 'date' => '06.09.2026', 'title' => 'Karenzzeit und Einreichfenster',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Karenzzeit vor dem Einzug, Nachtfenster, Storno im Status Vorgemerkt, Not-Stopp mit Sammelstorno (Migration 011).'],
            ['type' => 'Behoben', 'text' => 'Umterminieren setzt die Vormerkung zurück, Support-Sperre für Einreichungen, Asset-Versionierung gegen Browser-Cache.'],
         ]],
        ['version' => '2.1', 'date' => '05.09.2026', 'title' => 'Profil, Dashboard, Stripe-Import',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Profilmenü mit Bild und Telefonnummern, fünf Dashboard-Karten, Gläubiger-ID optional (Migration 010).'],
            ['type' => 'Neu', 'text' => 'Bestehende Einzüge aus Stripe übernehmen (Migration 009), Tarifeditor, Support-Bereich mit Firmenzugriff (Migration 008), automatischer Upload über GitHub.'],
         ]],
        ['version' => '2.0', 'date' => '05.09.2026', 'title' => 'SmartEinzug: Marke, Websites, Host-Trennung',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Hauptwebsite smart-einzug.de, Alias-Weiterleitungen, eigenständige Inhalte je Domain, app. und admin. als getrennte Hosts.'],
            ['type' => 'Neu', 'text' => 'Zahlungsqualität: Erstattungen aus Stripe, Klärung unklarer Versuche, Alarmierung, Zweitbestätigung kritischer Aktionen, Mandatsdokumente.'],
         ]],
        ['version' => '1.1', 'date' => '04.09.2026', 'title' => 'SaaS-Ausbau',
         'entries' => [
            ['type' => 'Neu', 'text' => '2FA-Pflicht, Rollen, Tarife, Audit, Plattform-Abrechnung mit Stripe Tax, Marketingseiten mit Einwilligungsbanner.'],
            ['type' => 'Behoben', 'text' => 'Sicherheitskorrekturen nach adversarialer Prüfung.'],
         ]],
        ['version' => '1.0', 'date' => '31.08.2026', 'title' => 'Erste Fassung für IONOS Webhosting',
         'entries' => [
            ['type' => 'Neu', 'text' => 'Lexware-Office-Synchronisation in fortsetzbaren Schritten, SEPA-Einzug je Kunde, Sammel-Einzug, mehrere Firmen je Konto, HVM-CI, Setup-Prüfung.'],
         ]],
    ];
}

/** Build-Informationen aus app/build.txt (vom Deployment geschrieben) oder null. */
function app_build_info(): ?string
{
    $f = __DIR__ . '/build.txt';
    $v = is_file($f) ? trim((string)@file_get_contents($f)) : '';
    return $v !== '' ? $v : null;
}
